version: "3.9"
services:
  neo4j:
    image: bitnami/neo4j:latest
    container_name: neo4j
    hostname: local.neo4j
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    env_file:
      - ./env/neo4j.env
    volumes:
      - ./neo4j/data:/bitnami/neo4j
      - ../scripts:/scripts
    networks:
      - "neo4j"

networks:
  neo4j:
    driver: "bridge"
